### PR TITLE
fix(messagelist): Clear message selection after user action

### LINKED ISSUE #1552: Moving messages include the previously moved message
**Describe the bug**
When moving a message to a folder with drag & drop and then moving (or deleting) another message, the previous message is also moved.

**To Reproduce**
1. Go to https://runbox.com/app/
2. Drag a message to folder A
3. Drag another message to folder B
4. Observe that both messages end up in folder B

**Expected behavior**
Only the selected message should be moved.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  macOS
 - Browser: Firefox

### PR DESCRIPTION
**Pull request by castaway**
Fixes #1552

### CODE REVIEW

File: src/app/app.component.ts [hunk 1]
```diff
@@ -1093,6 +1093,10 @@ export class AppComponent implements OnInit, AfterViewInit, CanvasTableSelectLis
           this.searchService.moveMessagesToFolder(msgIds, folderPath);
         }
         this.messagelistservice.moveMessages(msgIds, folderPath);
+        this.clearSelection();
+        if(this.singlemailviewer && this.singlemailviewer.messageId && messageIds.includes(this.singlemailviewer.messageId)) {
```
Comment (shadowbas) [inline src/app/app.component.ts:1097]: `this.singlemailviewer?.messageId` would be the same.

**Review by shadowbas — APPROVED** [review]

**Comment by runboxdave** [comment]
I think this works with the few user actions I've tried.
