### PR TITLE
fix(account): Only subscription/renewal pages for expired accounts

### LINKED ISSUE #1473: Can't renew when account is expired
**Describe the bug**
Visiting account/subscriptions should always work when the account is expired

**To Reproduce**
1. Login
2. See "Expired, visit 'Your Subscriptions'" message
3. Click on "Your Subscriptions"
4. Get distracted and click on any other page, eg Mail icon in menu
5. Get redirected to the Login page as your account has expired
6. Login again, click on "Your Subscriptions"
7. This now sends you back to login, no chance to renew

**Expected behavior**
Visiting the subscriptions page should always work on an expired account

### PR DESCRIPTION
**Pull request by castaway**
Expired accounts should only be able to visit account/subscriptions (and related pages) to process a renewal. This prevents starting the index updates or current message list, as these will delete the session cookie when called with an expired account, which prevents the user from visiting the subscriptions page.

Fixes #1473

### CODE REVIEW

**Review by gtandersen — APPROVED** [review]

File: src/app/rmmapi/rbwebmail.ts [hunk 1]
```diff
@@ -294,47 +296,55 @@ export class RunboxWebmailAPI {
...
-                    if (size === -1) {
-                        // Size = -1 means deleted flag is set - ref hack in Webmail.pm
-                        ret.deletedFlag = true;
-                    }
-                    return ret;
-                })
-            )
-        );
+          return this.me.pipe(
+            mergeMap((me) => {
```
Comment (antoniskalou) [inline src/app/rmmapi/rbwebmail.ts:300]: Seems fine to be, but couldn't you have done this as a filter?

```javascript
return this.me.pipe(
  filter(me => me.account_status !== 'expired'),
  mergeMap((me) => {
    // ...
  }
}
```

File: src/app/xapian/searchservice.ts [hunk 2]
```diff
@@ -103,6 +103,7 @@ export class SearchService {
   localdir: string;
   partitionsdir: string;
 
+  isExpired: boolean = false;
```
Comment (antoniskalou) [inline src/app/xapian/searchservice.ts:106]: If you feel like it, it might be a good idea to add that as a method in `RunboxMe` instead since there's seems to be a lot of `me.account_status === 'expired'`

**Review by antoniskalou — COMMENTED** [review]
Few minor things & some suggestions

File: src/app/rmmapi/rmmhttpinterceptor.service.ts [hunk 3]
```diff
@@ -76,6 +77,19 @@ export class RMMHttpInterceptorService implements HttpInterceptor {
                             this.checkAccountStatus();
                         }
                     }
+                    if (req.url === '/rest/v1/me' && r.body) {
+                        this.currentMe = r.body.result;
```
[the remark this answers is not in the document]
Comment (castaway) [reply src/app/rmmapi/rmmhttpinterceptor.service.ts:81]: Yes, am using .currentMe over different API calls, it should stick around for later use

**Review by antoniskalou — APPROVED** [review]
