### PR TITLE
fix(mailviewer): Sent folder now ignores "unread only" setting

### LINKED ISSUE #893: Unread option is also being applied to the Sent folder
The option to show only unread messages is also being applied to the Sent folder and this isn't appropriate. The result is you see no messages in your Sent folder.

### PR DESCRIPTION
**Pull request by castaway**
Fixes #893

### CODE REVIEW

**Review by gtandersen — APPROVED** [review]

File: src/app/xapian/searchservice.ts [hunk 1]
```diff
@@ -662,7 +662,7 @@ export class SearchService {
       querytext += folderQuery(folderPath);
     }
 
-    if (unreadOnly) {
+    if (unreadOnly && !this.messagelistservice.ignoreUnreadInFolders.includes(folderPath)) {
```
Comment (tadzik) [inline src/app/xapian/searchservice.ts:665]: I'm not too fond of this level of intimacy between this method and MessageListService.

Would it be very annoying to just not set unreadOnly when we're querying for the Sent folder?

Comment (castaway) [reply src/app/xapian/searchservice.ts:665]: Not particularly...

Comment (castaway) [reply src/app/xapian/searchservice.ts]: Logic moved up a level

**Review by tadzik — APPROVED** [review]
