### PR TITLE
fix(mailviewer): Maintain selected messages when new mail appears

### LINKED ISSUE #914: Maintain checkbox selection on message list update
When selecting one or more checkboxes in the message list and the list is updated with new messages before further action is taken, the selected checkboxes are automatically moved up the list accordingly.

Instead, the same checkboxes should remain selected to prevent action to be taken on the wrong messages.

### PR DESCRIPTION
**Pull request by castaway**
Fixes #914

### CODE REVIEW

**Review by gtandersen — APPROVED** [review]
Excellent, @castaway!

File: src/app/common/messagedisplay.ts [hunk 1]
```diff
@@ -36,20 +37,38 @@ export abstract class MessageDisplay {
...
+    return Object.keys(this.msgIdsSelected).filter((msgId) => this.msgIdsSelected[parseInt(msgId, 10)]).map((msgId) => parseInt(msgId, 10));
   }
 
   allSelected(): boolean {
-    return Object.keys(this.selectedRowIds).filter((key) => this.selectedRowIds[key]).length === this.rows.length;
+    return Object.keys(this.msgIdsSelected).filter((key) => this.msgIdsSelected[key]).length === this.rows.length;
+  }
+
+  anySelected(): boolean {
+    return Object.keys(this.msgIdsSelected).reduce((prev, current) =>
```
Comment (tadzik) [inline src/app/common/messagedisplay.ts:54]: I think this could be simplified to `!!Object.keys(this.msgIdsSelected).find(id => this.msgIdsSelected)` or something similar.

File: src/app/common/messagedisplay.ts [hunk 2]
```diff
@@ -36,20 +37,38 @@ export abstract class MessageDisplay {
     return this.rows.length;
   }
 
+  selectedRowIds(): number[] {
+    return Object.keys(this.selectedMessageIds).map((msgIndex) => this.findRowByMessageId(parseInt(msgIndex, 10)));
+  }
+
+  // msgIds where the value is true
```
Comment (tadzik) [inline src/app/common/messagedisplay.ts:44]: What value? ;)

File: src/app/common/messagedisplay.ts (hunk 1 above)
Comment (tadzik) [reply src/app/common/messagedisplay.ts:54]: Or even `this.selectedMessageIds().length > 0`

File: src/app/common/messagedisplay.ts [hunk 3]
```diff
@@ -36,20 +37,38 @@ export abstract class MessageDisplay {
     return this.rows.length;
   }
 
+  selectedRowIds(): number[] {
+    return Object.keys(this.selectedMessageIds).map((msgIndex) => this.findRowByMessageId(parseInt(msgIndex, 10)));
```
Comment (tadzik) [inline src/app/common/messagedisplay.ts:41]: Isn't `this.selectedMessageIds` a method? Did this mean to use this.`msgIdsSelected`?

This could be a good argument to give these more obvious names, right now we have attributes that look very similar to methods.

File: src/app/common/messagedisplay.ts (hunk 1 above)
Comment (castaway) [reply src/app/common/messagedisplay.ts:54]: Could even just be a "find where any is true" .. I just moved this code from app.component ... didnt re-read it ;)

File: src/app/common/messagedisplay.ts [hunk 4]
```diff
@@ -36,20 +37,38 @@ export abstract class MessageDisplay {
...
+  }
+
+  // msgIds where the value is true
   selectedMessageIds(): number[] {
-    return Object.keys(this.selectedRowIds).map((rowIndex) => this.getRowMessageId(parseInt(rowIndex, 10)));
+    return Object.keys(this.msgIdsSelected).filter((msgId) => this.msgIdsSelected[parseInt(msgId, 10)]).map((msgId) => parseInt(msgId, 10));
```
Comment (tadzik) [inline src/app/common/messagedisplay.ts:46]: I don't think these parseInts are necessary: unless we lie in the type definition of the attribute and these isn't actually `{ [number]: boolean }` ;)

**Review by tadzik — CHANGES_REQUESTED** [review]

File: src/app/common/messagedisplay.ts (hunk 1 above)
Comment (castaway) [reply src/app/common/messagedisplay.ts:54]: Object.values(this.msgIdsSelected).includes(true); ? feels like the shortest one

File: src/app/common/messagedisplay.ts (hunk 2 above)
Comment (castaway) [reply src/app/common/messagedisplay.ts:44]: *the* value! its a hash ;)

File: src/app/common/messagedisplay.ts (hunk 3 above)
Comment (castaway) [reply src/app/common/messagedisplay.ts:41]: Yes, oops (I renamed it mid fix)

File: src/app/common/messagedisplay.ts (hunk 4 above)
Comment (castaway) [reply src/app/common/messagedisplay.ts:46]: Object.keys makes things back into strings :(

**Review by tadzik — APPROVED** [review]
